"""Build (prompt, chosen, rejected) preference pairs for Phase E ORPO.

The Phase D SFT checkpoint is imperfect: its drafts under-cite, drift off
topic, or hallucinate numbers. Phase E teaches it to prefer a stronger
rewrite over its own draft via reference-free ORPO. The preference data
is generated by asking ``gpt-5-mini`` through the OpenAI Batch API to
critique + rewrite each SFT draft:

1. Run inference on the Phase D checkpoint over the training prompts
   (externally — this module takes the drafts JSONL as input).
2. :func:`build_critique_batch` emits a Batch API request JSONL that
   wraps each draft in a critique prompt, uploads it, and starts the
   batch.
3. :func:`poll_and_build_preferences` polls the batch to completion,
   pairs each rewrite with its source draft, and writes TRL-compatible
   ``{prompt, chosen, rejected}`` rows ready for
   :class:`trl.experimental.orpo.ORPOTrainer`.

Input ``drafts.jsonl`` schema (one row per SFT draft)::

    {
      "custom_id": "draft-00001",       # unique id per draft
      "prompt": "...",                   # the user turn shown to SFT
      "system": "...",                   # optional; defaults to SYSTEM_PROMPT
      "sft_draft": "..."                 # the SFT model's output to improve
    }
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from typing import Any, Iterable

from yuholens.training.sft_data import render_qwen_chatml
from yuholens.training.teacher import (
    SYSTEM_PROMPT,
    TEACHER_MODEL,
    _retry,
    poll_batch,
    write_results_jsonl,
)

CRITIQUE_SYSTEM = """You are a senior English-speaking Japan-equity analyst
reviewing a junior analyst's draft investor memo. Your task is to produce
an IMPROVED rewrite of the memo: same structure, stronger citations,
factually grounded in the Japanese source, no hallucinated numbers, every
material claim linked to a verbatim Japanese span in the
``(ref: '…' p.X)`` format.

Hard rules:
- Output ONLY the rewritten memo. No preface, no critique section, no
  markdown fences — just the memo itself.
- Preserve the 7-section structure of the draft.
- Every material claim references a Japanese span via inline parenthetical.
- Numerical values stated in ¥ million unless the source is ¥ billion
  explicitly; do not invent numbers.
- If a section's content cannot be grounded, write "not disclosed" for
  that section rather than fabricating content.
"""


def _critique_user_prompt(draft_row: dict[str, Any]) -> str:
    """Render the user turn that asks gpt-5-mini to rewrite a draft.

    Args:
        draft_row: One row from the drafts JSONL.

    Returns:
        The rendered user-turn string.
    """
    original_prompt = draft_row.get("prompt", "")
    sft_draft = draft_row.get("sft_draft", "")
    return (
        "Original user instruction given to the junior analyst:\n<<<\n"
        f"{original_prompt}\n>>>\n\n"
        "Junior analyst's draft memo:\n<<<\n"
        f"{sft_draft}\n>>>\n\n"
        "Produce the improved rewrite now."
    )


def build_critique_batch(
    drafts_path: Path,
    out_path: Path,
    limit: int | None = None,
) -> None:
    """Submit an OpenAI batch that asks gpt-5-mini to rewrite each SFT draft.

    Writes ``out_path.with_suffix('.requests.jsonl')`` with the per-draft
    chat requests, uploads it with ``purpose='batch'``, creates the batch
    job, and persists ``{batch_id, input_file_id, drafts_path}`` to
    ``out_path`` for :func:`poll_and_build_preferences` to consume.

    Args:
        drafts_path: JSONL of SFT drafts; see module docstring for schema.
        out_path: Destination JSON manifest for the batch.
        limit: Optional cap on drafts to submit; useful for smoke runs.
    """
    import openai

    client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    requests_path = out_path.with_suffix(".requests.jsonl")

    count = 0
    with drafts_path.open("r", encoding="utf-8") as drafts_fh, requests_path.open(
        "w", encoding="utf-8"
    ) as out_fh:
        for line in drafts_fh:
            line = line.strip()
            if not line:
                continue
            if limit is not None and count >= limit:
                break
            draft_row = json.loads(line)
            custom_id = draft_row.get("custom_id")
            if not isinstance(custom_id, str):
                continue
            req = {
                "custom_id": custom_id,
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": TEACHER_MODEL,
                    "max_completion_tokens": 4000,
                    "reasoning_effort": "minimal",
                    "messages": [
                        {"role": "system", "content": CRITIQUE_SYSTEM},
                        {"role": "user", "content": _critique_user_prompt(draft_row)},
                    ],
                },
            }
            out_fh.write(json.dumps(req, ensure_ascii=False) + "\n")
            count += 1

    with requests_path.open("rb") as upload_fh:
        file_obj = client.files.create(file=upload_fh, purpose="batch")
    batch = client.batches.create(
        input_file_id=file_obj.id,
        endpoint="/v1/chat/completions",
        completion_window="24h",
    )
    out_path.write_text(
        json.dumps(
            {
                "batch_id": batch.id,
                "input_file_id": file_obj.id,
                "drafts_path": str(drafts_path),
            }
        )
        + "\n"
    )


def _index_drafts(drafts_path: Path) -> dict[str, dict[str, Any]]:
    """Index a drafts JSONL by ``custom_id``."""
    index: dict[str, dict[str, Any]] = {}
    with drafts_path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            custom_id = row.get("custom_id")
            if isinstance(custom_id, str):
                index[custom_id] = row
    return index


def _build_preference_rows(
    critique_results: Iterable[dict[str, Any]],
    drafts_index: dict[str, dict[str, Any]],
    system_prompt_default: str,
) -> list[dict[str, Any]]:
    """Pair critiques with drafts and assemble TRL preference rows."""
    records: list[dict[str, Any]] = []
    for result in critique_results:
        rewrite = result.get("memo")
        custom_id = result.get("custom_id")
        if not isinstance(custom_id, str) or not isinstance(rewrite, str) or not rewrite.strip():
            continue
        draft_row = drafts_index.get(custom_id)
        if draft_row is None:
            continue
        prompt_user = draft_row.get("prompt", "")
        sft_draft = draft_row.get("sft_draft", "")
        system = draft_row.get("system") or system_prompt_default
        prompt_text = render_qwen_chatml(
            [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt_user},
            ]
        ) + "<|im_start|>assistant\n"
        records.append(
            {
                "custom_id": custom_id,
                "prompt": prompt_text,
                "chosen": rewrite + "<|im_end|>",
                "rejected": sft_draft + "<|im_end|>",
            }
        )
    return records


def poll_and_build_preferences(
    batch_json: Path,
    drafts_path: Path,
    preferences_out: Path,
    raw_out: Path | None = None,
    system_prompt_default: str = SYSTEM_PROMPT,
    poll_interval_s: float = 60.0,
    max_wait_s: float = 90_000.0,
) -> dict[str, int]:
    """Poll the critique batch and write ``(prompt, chosen, rejected)`` rows.

    Args:
        batch_json: Path emitted by :func:`build_critique_batch`.
        drafts_path: Input drafts JSONL used to resolve ``custom_id`` →
            original prompt + SFT draft for pairing.
        preferences_out: Destination JSONL in TRL ORPO format.
        raw_out: Optional JSONL for the raw batch results (same schema as
            :func:`~yuholens.training.teacher.poll_batch`).
        system_prompt_default: System prompt prepended to the constructed
            ``prompt`` field when the draft row does not pin one.
        poll_interval_s: Seconds between batch status checks.
        max_wait_s: Hard cap for the batch wait.

    Returns:
        A dict with keys ``polled``, ``raw_written`` (0 if ``raw_out`` is
        ``None``), and ``preferences``.
    """
    info = json.loads(batch_json.read_text(encoding="utf-8"))
    batch_id = info["batch_id"]

    import openai

    client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    start = time.monotonic()
    while True:
        handle = _retry(lambda: client.batches.retrieve(batch_id))
        status = getattr(handle, "status", None)
        if status in {"completed", "failed", "expired", "canceled"}:
            break
        if time.monotonic() - start >= max_wait_s:
            raise TimeoutError(f"critique batch {batch_id} did not terminate")
        time.sleep(poll_interval_s)
    if status != "completed":
        raise RuntimeError(f"critique batch {batch_id} terminated with status={status}")

    results = poll_batch(batch_id, client=client)
    raw_written = 0
    if raw_out is not None:
        raw_written = write_results_jsonl(results, raw_out, overwrite=True)

    drafts_index = _index_drafts(drafts_path)
    preferences = _build_preference_rows(
        results, drafts_index, system_prompt_default=system_prompt_default
    )
    preferences_out.parent.mkdir(parents=True, exist_ok=True)
    with preferences_out.open("w", encoding="utf-8") as fh:
        for record in preferences:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")

    return {
        "polled": len(results),
        "raw_written": raw_written,
        "preferences": len(preferences),
    }


def main() -> None:
    """CLI: ``build-critique-batch`` / ``poll-and-build``."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="cmd", required=True)

    build_parser = subparsers.add_parser(
        "build-critique-batch",
        help="Submit a gpt-5-mini Batch API job to rewrite each SFT draft.",
    )
    build_parser.add_argument("--drafts", type=Path, required=True)
    build_parser.add_argument("--out", type=Path, required=True)
    build_parser.add_argument("--limit", type=int, default=None)

    poll_parser = subparsers.add_parser(
        "poll-and-build",
        help="Poll the critique batch and emit TRL preference rows.",
    )
    poll_parser.add_argument("--batch-json", type=Path, required=True)
    poll_parser.add_argument("--drafts", type=Path, required=True)
    poll_parser.add_argument("--preferences-out", type=Path, required=True)
    poll_parser.add_argument("--raw-out", type=Path, default=None)

    args = parser.parse_args()

    if args.cmd == "build-critique-batch":
        build_critique_batch(args.drafts, args.out, args.limit)
    elif args.cmd == "poll-and-build":
        result = poll_and_build_preferences(
            args.batch_json,
            args.drafts,
            args.preferences_out,
            raw_out=args.raw_out,
        )
        print(
            f"polled={result['polled']} raw={result['raw_written']} "
            f"preferences={result['preferences']}"
        )


if __name__ == "__main__":
    main()
