"""Build (prompt, chosen, rejected) preference pairs for Phase E ORPO.

The Phase D SFT checkpoint is imperfect: its drafts under-cite, drift off
topic, or hallucinate numbers. Phase E teaches it to prefer a stronger
rewrite over its own draft via reference-free ORPO. The preference data
is generated by asking ``gpt-5-mini`` through the OpenAI Batch API to
critique + rewrite each SFT draft:

1. Run inference on the Phase D checkpoint over the training prompts
   (externally — this module takes the drafts JSONL as input).
2. :func:`build_critique_batch` emits a Batch API request JSONL that
   wraps each draft in a critique prompt, uploads it, and starts the
   batch.
3. :func:`poll_and_build_preferences` polls the batch to completion,
   pairs each rewrite with its source draft, and writes TRL-compatible
   ``{prompt, chosen, rejected}`` rows ready for
   :class:`trl.experimental.orpo.ORPOTrainer`.

Input ``drafts.jsonl`` schema (one row per SFT draft)::

    {
      "custom_id": "draft-00001",       # unique id per draft
      "prompt": "...",                   # the user turn shown to SFT
      "system": "...",                   # optional; defaults to SYSTEM_PROMPT
      "sft_draft": "..."                 # the SFT model's output to improve
    }
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path
from typing import Any, Iterable

from yuholens.training.sft_data import render_qwen_chatml
from yuholens.training.teacher import (
    SYSTEM_PROMPT,
    TEACHER_MODEL,
    _retry,
    poll_batch,
    write_results_jsonl,
)

CRITIQUE_SYSTEM = """You are a senior English-speaking Japan-equity analyst
reviewing a junior analyst's draft investor memo. Your task is to produce
an IMPROVED rewrite of the memo whose argument is more STRUCTURALLY COHERENT
than the draft. The rewrite is judged by a downstream rubric that scores ONLY
cross-section argument unity — not citation count, not factual correctness,
not prose polish, not grammar. Optimise for the rubric below.

Coherence rubric you must satisfy
---------------------------------
Every memo follows a fixed seven-section structure:
    1. Executive summary (3 to 5 sentences distilling the investment thesis).
    2. Going-concern assessment (liquidity, covenants, auditor remarks,
       ability-to-continue flags).
    3. Accrual quality (DSO change, inventory days, receivables aging,
       accrual versus cash-flow patterns).
    4. Earnings direction call (up / down / flat next period, with explicit
       reasoning tied to revenue, margin, and mix drivers).
    5. Top 3 risks from 事業等のリスク (ranked, short rationale).
    6. Related-party transactions summary (or "not disclosed").
    7. Evidence appendix (bulleted Japanese span citations grounding body
       claims).

A coherent rewrite must, relative to the draft:

- Carry CONSISTENT DIRECTIONAL CLAIMS across sections 3, 4, and 5. The
  earnings-direction call in section 4 must be reinforced — not silently
  contradicted — by the accrual-quality discussion in section 3 and the risk
  ranking in section 5. If the draft predicts accelerating earnings while
  flagging rising DSO without reconciliation, fix the contradiction.
- Build a COMPLETE EVIDENCE LADDER: the executive summary previews the
  thesis, the body sections develop and support each summary claim, and
  every material claim in the body is grounded by a span in the evidence
  appendix. Drop summary claims with no body support; drop appendix entries
  unrelated to body claims.
- Use STABLE TERMINOLOGY for the same concept across sections. If the draft
  uses "operating margin" in section 1 and silently switches to "EBIT
  margin" in section 4, pick one and use it everywhere.
- ALIGN going-concern (section 2) WITH RISK RANKING (section 5). A draft
  that flags catastrophic liquidity in section 2 but ranks currency
  translation as the top risk in section 5 is internally inconsistent;
  re-rank or reframe so the two sections agree.
- NAME AND RESOLVE TENSIONS rather than hiding them. If revenue grew but
  cash flow from operations fell, do not assert both "strong growth" and
  "healthy cash generation"; acknowledge the gap and reconcile it.
- PRESERVE the seven-section structure. Do not invent new sections, drop
  required sections, or merge sections.

What you must NOT change
------------------------
- PRESERVE EVERY (refs: ...) citation marker that appears in the draft. Do
  not delete, rename, merge, reword, or reorder existing citation tags.
  Each distinct (refs: ...) span present in the draft must appear in the
  rewrite at least as many times as it appears in the draft. If a body
  claim genuinely cannot be supported, replace the claim with "not
  disclosed" but keep the associated (refs: ...) marker attached to the
  same section. Stripping or dropping citations is the single most damaging
  failure mode here and will be detected by a downstream gate; a rewrite
  that loses citations will be rejected.
- Do not invent new numerical values, new citations, or new Japanese spans.
  Reuse only the citations and figures already present in the draft.
- Do not lengthen the memo for the sake of length, and do not aggressively
  shorten it. Coherence is structural, not a word-count target.
- Do not "polish" English grammar beyond what is needed for the argument to
  parse. Citation count and prose polish are scored by other metrics; they
  are not your job here.

Hard output rules
-----------------
- Output ONLY the rewritten memo. No preface, no critique section, no
  markdown fences, no commentary — just the memo itself.
- Preserve the seven-section structure of the draft.
- If a section's content genuinely cannot be supported by spans available
  in the draft, write "not disclosed" for that section rather than
  fabricating content. Section 6 in particular is allowed to be "not
  disclosed" without penalty.
"""


def _critique_user_prompt(draft_row: dict[str, Any]) -> str:
    """Render the user turn that asks gpt-5-mini to rewrite a draft.

    Args:
        draft_row: One row from the drafts JSONL.

    Returns:
        The rendered user-turn string.
    """
    original_prompt = draft_row.get("prompt", "")
    sft_draft = draft_row.get("sft_draft", "")
    return (
        "Original user instruction given to the junior analyst:\n<<<\n"
        f"{original_prompt}\n>>>\n\n"
        "Junior analyst's draft memo:\n<<<\n"
        f"{sft_draft}\n>>>\n\n"
        "Produce the improved rewrite now."
    )


def build_critique_batch(
    drafts_path: Path,
    out_path: Path,
    limit: int | None = None,
) -> None:
    """Submit an OpenAI batch that asks gpt-5-mini to rewrite each SFT draft.

    Writes ``out_path.with_suffix('.requests.jsonl')`` with the per-draft
    chat requests, uploads it with ``purpose='batch'``, creates the batch
    job, and persists ``{batch_id, input_file_id, drafts_path}`` to
    ``out_path`` for :func:`poll_and_build_preferences` to consume.

    Args:
        drafts_path: JSONL of SFT drafts; see module docstring for schema.
        out_path: Destination JSON manifest for the batch.
        limit: Optional cap on drafts to submit; useful for smoke runs.
    """
    import openai

    client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    requests_path = out_path.with_suffix(".requests.jsonl")

    count = 0
    with drafts_path.open("r", encoding="utf-8") as drafts_fh, requests_path.open(
        "w", encoding="utf-8"
    ) as out_fh:
        for line in drafts_fh:
            line = line.strip()
            if not line:
                continue
            if limit is not None and count >= limit:
                break
            draft_row = json.loads(line)
            custom_id = draft_row.get("custom_id")
            if not isinstance(custom_id, str):
                continue
            req = {
                "custom_id": custom_id,
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": TEACHER_MODEL,
                    "max_completion_tokens": 4000,
                    "reasoning_effort": "minimal",
                    "messages": [
                        {"role": "system", "content": CRITIQUE_SYSTEM},
                        {"role": "user", "content": _critique_user_prompt(draft_row)},
                    ],
                },
            }
            out_fh.write(json.dumps(req, ensure_ascii=False) + "\n")
            count += 1

    with requests_path.open("rb") as upload_fh:
        file_obj = client.files.create(file=upload_fh, purpose="batch")
    batch = client.batches.create(
        input_file_id=file_obj.id,
        endpoint="/v1/chat/completions",
        completion_window="24h",
    )
    out_path.write_text(
        json.dumps(
            {
                "batch_id": batch.id,
                "input_file_id": file_obj.id,
                "drafts_path": str(drafts_path),
            }
        )
        + "\n"
    )


def _index_drafts(drafts_path: Path) -> dict[str, dict[str, Any]]:
    """Index a drafts JSONL by ``custom_id``."""
    index: dict[str, dict[str, Any]] = {}
    with drafts_path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            custom_id = row.get("custom_id")
            if isinstance(custom_id, str):
                index[custom_id] = row
    return index


def _build_preference_rows(
    critique_results: Iterable[dict[str, Any]],
    drafts_index: dict[str, dict[str, Any]],
    system_prompt_default: str,
) -> list[dict[str, Any]]:
    """Pair critiques with drafts and assemble TRL preference rows."""
    records: list[dict[str, Any]] = []
    for result in critique_results:
        rewrite = result.get("memo")
        custom_id = result.get("custom_id")
        if not isinstance(custom_id, str) or not isinstance(rewrite, str) or not rewrite.strip():
            continue
        draft_row = drafts_index.get(custom_id)
        if draft_row is None:
            continue
        prompt_user = draft_row.get("prompt", "")
        sft_draft = draft_row.get("sft_draft", "")
        system = draft_row.get("system") or system_prompt_default
        prompt_text = render_qwen_chatml(
            [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt_user},
            ]
        ) + "<|im_start|>assistant\n"
        records.append(
            {
                "custom_id": custom_id,
                "prompt": prompt_text,
                "chosen": rewrite + "<|im_end|>",
                "rejected": sft_draft + "<|im_end|>",
            }
        )
    return records


def poll_and_build_preferences(
    batch_json: Path,
    drafts_path: Path,
    preferences_out: Path,
    raw_out: Path | None = None,
    system_prompt_default: str = SYSTEM_PROMPT,
    poll_interval_s: float = 60.0,
    max_wait_s: float = 90_000.0,
) -> dict[str, int]:
    """Poll the critique batch and write ``(prompt, chosen, rejected)`` rows.

    Args:
        batch_json: Path emitted by :func:`build_critique_batch`.
        drafts_path: Input drafts JSONL used to resolve ``custom_id`` →
            original prompt + SFT draft for pairing.
        preferences_out: Destination JSONL in TRL ORPO format.
        raw_out: Optional JSONL for the raw batch results (same schema as
            :func:`~yuholens.training.teacher.poll_batch`).
        system_prompt_default: System prompt prepended to the constructed
            ``prompt`` field when the draft row does not pin one.
        poll_interval_s: Seconds between batch status checks.
        max_wait_s: Hard cap for the batch wait.

    Returns:
        A dict with keys ``polled``, ``raw_written`` (0 if ``raw_out`` is
        ``None``), and ``preferences``.
    """
    info = json.loads(batch_json.read_text(encoding="utf-8"))
    batch_id = info["batch_id"]

    import openai

    client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    start = time.monotonic()
    while True:
        handle = _retry(lambda: client.batches.retrieve(batch_id))
        status = getattr(handle, "status", None)
        if status in {"completed", "failed", "expired", "canceled"}:
            break
        if time.monotonic() - start >= max_wait_s:
            raise TimeoutError(f"critique batch {batch_id} did not terminate")
        time.sleep(poll_interval_s)
    if status != "completed":
        raise RuntimeError(f"critique batch {batch_id} terminated with status={status}")

    results = poll_batch(batch_id, client=client)
    raw_written = 0
    if raw_out is not None:
        raw_written = write_results_jsonl(results, raw_out, overwrite=True)

    drafts_index = _index_drafts(drafts_path)
    preferences = _build_preference_rows(
        results, drafts_index, system_prompt_default=system_prompt_default
    )
    preferences_out.parent.mkdir(parents=True, exist_ok=True)
    with preferences_out.open("w", encoding="utf-8") as fh:
        for record in preferences:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")

    return {
        "polled": len(results),
        "raw_written": raw_written,
        "preferences": len(preferences),
    }


def main() -> None:
    """CLI: ``build-critique-batch`` / ``poll-and-build``."""
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="cmd", required=True)

    build_parser = subparsers.add_parser(
        "build-critique-batch",
        help="Submit a gpt-5-mini Batch API job to rewrite each SFT draft.",
    )
    build_parser.add_argument("--drafts", type=Path, required=True)
    build_parser.add_argument("--out", type=Path, required=True)
    build_parser.add_argument("--limit", type=int, default=None)

    poll_parser = subparsers.add_parser(
        "poll-and-build",
        help="Poll the critique batch and emit TRL preference rows.",
    )
    poll_parser.add_argument("--batch-json", type=Path, required=True)
    poll_parser.add_argument("--drafts", type=Path, required=True)
    poll_parser.add_argument("--preferences-out", type=Path, required=True)
    poll_parser.add_argument("--raw-out", type=Path, default=None)

    args = parser.parse_args()

    if args.cmd == "build-critique-batch":
        build_critique_batch(args.drafts, args.out, args.limit)
    elif args.cmd == "poll-and-build":
        result = poll_and_build_preferences(
            args.batch_json,
            args.drafts,
            args.preferences_out,
            raw_out=args.raw_out,
        )
        print(
            f"polled={result['polled']} raw={result['raw_written']} "
            f"preferences={result['preferences']}"
        )


if __name__ == "__main__":
    main()
